# Generated by Django 4.0.5 on 2022-06-25 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('known_for_department', models.CharField(max_length=255)),
                ('adult', models.BooleanField(blank=True, null=True)),
                ('gender', models.IntegerField()),
                ('original_name', models.CharField(max_length=255)),
                ('popularity', models.FloatField(blank=True)),
                ('profile_path', models.TextField(blank=True, null=True)),
                ('credit_id', models.CharField(max_length=255)),
                ('character', models.CharField(max_length=255)),
                ('cast_id', models.IntegerField(blank=True)),
                ('order', models.IntegerField(blank=True)),
            ],
            options={
                'verbose_name': 'Cast',
                'verbose_name_plural': 'Casts',
            },
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('job', models.CharField(max_length=255)),
                ('known_for_department', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('adult', models.BooleanField(blank=True, null=True)),
                ('gender', models.IntegerField()),
                ('original_name', models.CharField(max_length=255)),
                ('popularity', models.FloatField(blank=True)),
                ('profile_path', models.TextField(blank=True, null=True)),
                ('credit_id', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Crew',
                'verbose_name_plural': 'Crews',
            },
        ),
        migrations.CreateModel(
            name='SpokenLanguage',
            fields=[
                ('iso_639_1', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Language parlé',
                'verbose_name_plural': 'Languages parlés',
            },
        ),
        migrations.CreateModel(
            name='Watched',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('media_id', models.IntegerField()),
                ('media_type', models.CharField(choices=[('movie', 'Movie'), ('show', 'Show'), ('both', 'Both')], default='movie', max_length=5)),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='date published')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visionnage',
                'verbose_name_plural': 'Visionnés',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('content', models.CharField(max_length=1000)),
                ('media_id', models.IntegerField()),
                ('media_type', models.CharField(choices=[('movie', 'Movie'), ('show', 'Show'), ('both', 'Both')], default='movie', max_length=5)),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='date published')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('media_id', models.IntegerField()),
                ('media_type', models.CharField(choices=[('movie', 'Movie'), ('show', 'Show'), ('both', 'Both')], default='movie', max_length=5)),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='date published')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favori',
                'verbose_name_plural': 'Favoris',
            },
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('movie', 'Movie'), ('show', 'Show'), ('both', 'Both')], default='movie', max_length=5)),
                ('cast', models.ManyToManyField(to='management.cast')),
                ('crew', models.ManyToManyField(to='management.crew')),
            ],
            options={
                'verbose_name': 'Credit',
                'verbose_name_plural': 'Credits',
            },
        ),
    ]
