# Generated by Django 4.0.4 on 2022-05-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_watched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watched',
            name='pub_date',
            field=models.DateTimeField(auto_now=True, verbose_name='date published'),
        ),
    ]
