# Generated by Django 4.0.4 on 2022-06-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_watched_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('movie', 'Movie'), ('tv', 'Show')], default='movie', max_length=5)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
