# Generated by Django 4.0.4 on 2022-06-07 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_genres'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genres',
            new_name='Genre',
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Genre', 'verbose_name_plural': 'Genres'},
        ),
    ]
