# Generated by Django 4.0.4 on 2022-06-08 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_rename_genres_genre_alter_genre_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='media_type',
            field=models.CharField(choices=[('movie', 'Movie'), ('tv', 'Show'), ('both', 'Both')], default='movie', max_length=5),
        ),
        migrations.AlterField(
            model_name='review',
            name='media_type',
            field=models.CharField(choices=[('movie', 'Movie'), ('tv', 'Show'), ('both', 'Both')], default='movie', max_length=5),
        ),
        migrations.AlterField(
            model_name='watched',
            name='media_type',
            field=models.CharField(choices=[('movie', 'Movie'), ('tv', 'Show'), ('both', 'Both')], default='movie', max_length=5),
        ),
    ]
