# Generated by Django 4.0.5 on 2022-06-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_genre_media_type_alter_review_media_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('known_for_department', models.CharField(max_length=255)),
                ('job', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('adult', models.BooleanField(blank=True)),
                ('gender', models.IntegerField()),
                ('original_name', models.CharField(max_length=255)),
                ('popularity', models.FloatField(blank=True)),
                ('profile_path', models.TextField(blank=True, null=True)),
                ('credit_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('job', models.CharField(max_length=255)),
                ('known_for_department', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('adult', models.BooleanField(blank=True)),
                ('gender', models.IntegerField()),
                ('original_name', models.CharField(max_length=255)),
                ('popularity', models.FloatField(blank=True)),
                ('profile_path', models.TextField(blank=True, null=True)),
                ('credit_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('movie', 'Movie'), ('tv', 'Show'), ('both', 'Both')], default='movie', max_length=5)),
                ('cast', models.ManyToManyField(to='management.cast')),
                ('crew', models.ManyToManyField(to='management.crew')),
            ],
            options={
                'verbose_name': 'Credit',
                'verbose_name_plural': 'Credits',
            },
        ),
    ]
