# Generated by Django 4.0.5 on 2022-06-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_delete_cast_alter_credit_cast'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('known_for_department', models.CharField(max_length=255)),
                ('job', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('adult', models.BooleanField(blank=True)),
                ('gender', models.IntegerField()),
                ('original_name', models.CharField(max_length=255)),
                ('popularity', models.FloatField(blank=True)),
                ('profile_path', models.TextField(blank=True, null=True)),
                ('credit_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='credit',
            name='cast',
            field=models.ManyToManyField(to='management.cast'),
        ),
    ]
