# Generated by Django 4.0.5 on 2022-06-10 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_cast_alter_credit_cast'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='cast_id',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cast',
            name='character',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cast',
            name='order',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
