# Generated by Django 4.0.5 on 2022-06-10 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_cast_cast_id_cast_character_cast_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cast',
            name='department',
        ),
    ]
