# Generated by Django 4.0.5 on 2022-06-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_remove_cast_job'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cast',
            options={'verbose_name': 'Cast', 'verbose_name_plural': 'Casts'},
        ),
        migrations.AlterModelOptions(
            name='crew',
            options={'verbose_name': 'Crew', 'verbose_name_plural': 'Crews'},
        ),
        migrations.AlterField(
            model_name='cast',
            name='adult',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crew',
            name='adult',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
