# Generated by Django 4.0.5 on 2022-06-13 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_alter_cast_options_alter_crew_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
