# Generated by Django 4.0.5 on 2022-06-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0016_remove_show_languages_show_languages'),
        ('management', '0015_language_alter_review_options_alter_watched_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpokenLanguage',
            fields=[
                ('iso_639_1', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Language parlé',
                'verbose_name_plural': 'Languages parlés',
            },
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
