# Generated by Django 4.0.5 on 2022-06-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_spokenlanguage_delete_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='media_type',
            field=models.CharField(choices=[('movie', 'Movie'), ('show', 'Show'), ('both', 'Both')], default='movie', max_length=5),
        ),
        migrations.AlterField(
            model_name='review',
            name='media_type',
            field=models.CharField(choices=[('movie', 'Movie'), ('show', 'Show'), ('both', 'Both')], default='movie', max_length=5),
        ),
        migrations.AlterField(
            model_name='watched',
            name='media_type',
            field=models.CharField(choices=[('movie', 'Movie'), ('show', 'Show'), ('both', 'Both')], default='movie', max_length=5),
        ),
    ]
