# Generated by Django 4.0.5 on 2022-06-18 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0017_alter_credit_media_type_alter_review_media_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('media_id', models.IntegerField()),
                ('media_type', models.CharField(choices=[('movie', 'Movie'), ('show', 'Show'), ('both', 'Both')], default='movie', max_length=5)),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='date published')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favori',
                'verbose_name_plural': 'Favoris',
            },
        ),
    ]
