# Generated by Django 4.0.5 on 2022-06-18 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0021_alter_review_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='name',
        ),
    ]
