# Generated by Django 4.0.4 on 2022-06-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_alter_show_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='number_of_episodes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='number_of_seasons',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
