# Generated by Django 4.0.4 on 2022-06-07 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0003_alter_show_number_of_episodes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='adult',
        ),
    ]
