# Generated by Django 4.0.4 on 2022-06-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0004_remove_show_adult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='backdrop_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
