# Generated by Django 4.0.4 on 2022-06-08 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0005_alter_show_backdrop_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='poster_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
