# Generated by Django 4.0.5 on 2022-06-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0006_alter_show_poster_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='genres',
        ),
        migrations.AddField(
            model_name='show',
            name='homepage',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='show',
            name='in_production',
            field=models.BooleanField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='show',
            name='languages',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='show',
            name='status',
            field=models.CharField(blank=True, choices=[('Rumored', 'Rumored'), ('Planned', 'Planned'), ('In Production', 'Inproduction'), ('Post Production', 'Postproduction'), ('Released', 'Released'), ('Canceled', 'Canceled')], max_length=255),
        ),
        migrations.AddField(
            model_name='show',
            name='tagline',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='show',
            name='type',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
