# Generated by Django 4.0.5 on 2022-06-13 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0008_alter_show_first_air_date_alter_show_last_air_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='first_air_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='last_air_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
