# Generated by Django 4.0.5 on 2022-06-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0010_genre_remove_show_genre_ids_show_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='status',
            field=models.CharField(blank=True, choices=[('Rumored', 'Rumored'), ('Planned', 'Planned'), ('In Production', 'Inproduction'), ('Post Production', 'Postproduction'), ('Released', 'Released'), ('Canceled', 'Canceled')], max_length=255, null=True),
        ),
    ]
