# Generated by Django 4.0.5 on 2022-06-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0011_alter_show_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='status',
            field=models.CharField(blank=True, choices=[('Rumored', 'Rumored'), ('Planned', 'Planned'), ('In Production', 'Inproduction'), ('Post Production', 'Postproduction'), ('Released', 'Released'), ('Canceled', 'Canceled'), ('Returning Series', 'Returningseries'), ('Ended', 'Ended')], max_length=255, null=True),
        ),
    ]
