# Generated by Django 4.0.5 on 2022-06-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0012_alter_show_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='status',
            field=models.CharField(blank=True, choices=[('Rumored', 'Rumeur'), ('Planned', 'Planifié'), ('In Production', 'En production'), ('Post Production', 'Post production'), ('Released', 'Sorti'), ('Canceled', 'Annulé'), ('Returning Series', 'Série en cours'), ('Ended', 'Terminé')], max_length=255, null=True),
        ),
    ]
