# Generated by Django 4.0.5 on 2022-06-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0013_alter_show_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='in_production',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
