# Generated by Django 4.0.5 on 2022-06-17 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0014_alter_show_in_production'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='languages',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
