# Generated by Django 4.0.5 on 2022-06-17 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_language_alter_review_options_alter_watched_options'),
        ('shows', '0015_alter_show_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='languages',
        ),
        migrations.AddField(
            model_name='show',
            name='languages',
            field=models.ManyToManyField(blank=True, to='management.language'),
        ),
    ]
