# Generated by Django 4.0.5 on 2022-06-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_spokenlanguage_delete_language'),
        ('shows', '0016_remove_show_languages_show_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='languages',
            field=models.ManyToManyField(blank=True, to='management.spokenlanguage'),
        ),
    ]
