# Generated by Django 4.0.5 on 2022-06-18 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0017_alter_show_languages'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('air_date', models.DateField()),
                ('season_number', models.IntegerField()),
                ('episode_number', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('overview', models.TextField()),
                ('production_code', models.CharField(max_length=255)),
                ('still_path', models.CharField(blank=True, max_length=255, null=True)),
                ('vote_average', models.FloatField()),
                ('vote_count', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='show',
            name='last_episode',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shows.lastepisode'),
        ),
    ]
