# Generated by Django 4.0.5 on 2022-06-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0018_lastepisode_show_last_episode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('air_date', models.DateField()),
                ('episode_count', models.IntegerField()),
                ('season_number', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('overview', models.TextField()),
                ('poster_path', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='show',
            name='seasons',
            field=models.ManyToManyField(blank=True, to='shows.season'),
        ),
    ]
