# Generated by Django 4.0.5 on 2022-06-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0019_season_show_seasons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='air_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
