# Generated by Django 4.0.4 on 2022-06-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('profile_path', models.TextField(blank=True, null=True)),
                ('popularity', models.FloatField(blank=True)),
                ('known_for_department', models.CharField(blank=True, max_length=255)),
                ('adult', models.BooleanField(blank=True)),
                ('birthday', models.TextField(blank=True, null=True)),
                ('biography', models.TextField(blank=True, null=True)),
                ('deathday', models.TextField(blank=True, null=True)),
                ('homepage', models.TextField(blank=True, null=True)),
                ('gender', models.IntegerField()),
                ('imdb_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
