# Generated by Django 4.0.5 on 2022-06-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('biography', models.TextField(blank=True, null=True)),
                ('deathday', models.DateField(blank=True, null=True)),
                ('known_for_department', models.CharField(blank=True, max_length=255, null=True)),
                ('adult', models.BooleanField(blank=True)),
                ('gender', models.IntegerField(null=True)),
                ('profile_path', models.TextField(blank=True, null=True)),
                ('also_known_as', models.TextField(blank=True, null=True)),
                ('popularity', models.FloatField(blank=True)),
                ('homepage', models.TextField(blank=True, null=True)),
                ('imdb_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
