# Generated by Django 4.0.5 on 2022-06-13 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0003_alter_actor_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='also_known_as',
            field=models.TextField(blank=True, null=True),
        ),
    ]
