# Generated by Django 4.0.5 on 2022-06-13 04:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0004_actor_also_known_as'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actor',
            name='deathday',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
