# Generated by Django 4.0.1 on 2022-03-09 10:03

from django.db import migrations, models
import movies.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('overview', models.CharField(max_length=200)),
                ('poster_path', models.CharField(max_length=200)),
                ('popularity', models.FloatField(max_length=200)),
                ('backdrop_path', models.CharField(max_length=200)),
                ('vote_average', models.FloatField()),
                ('release_date', models.CharField(max_length=200)),
                ('original_language', models.CharField(max_length=200)),
                ('genre_ids', models.JSONField(max_length=200)),
                ('vote_count', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('original_title', models.CharField(max_length=200)),
                ('origin_country', models.JSONField()),
                ('video', models.BooleanField()),
                ('adult', models.BooleanField()),
                ('budget', models.IntegerField()),
                ('revenue', models.IntegerField()),
                ('runtime', models.IntegerField()),
                ('status', models.CharField(max_length=200)),
                ('tagline', models.CharField(max_length=200)),
            ],
            bases=(models.Model, movies.models.BaseTMDB),
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
