# Generated by Django 4.0.5 on 2022-06-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('overview', models.TextField(blank=True)),
                ('homepage', models.CharField(blank=True, max_length=255)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('original_language', models.CharField(blank=True, max_length=255)),
                ('original_title', models.CharField(blank=True, max_length=255)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Rumored', 'Rumeur'), ('Planned', 'Planifié'), ('In Production', 'En production'), ('Post Production', 'Post production'), ('Released', 'Sorti'), ('Canceled', 'Annulé')], max_length=255, null=True)),
                ('adult', models.BooleanField(blank=True)),
                ('popularity', models.FloatField(blank=True)),
                ('vote_count', models.IntegerField(blank=True)),
                ('vote_average', models.FloatField(blank=True)),
                ('runtime', models.IntegerField(blank=True, null=True)),
                ('revenue', models.IntegerField(blank=True, null=True)),
                ('budget', models.IntegerField(blank=True, null=True)),
                ('video', models.BooleanField(null=True)),
                ('poster_path', models.TextField(blank=True, null=True)),
                ('backdrop_path', models.TextField(blank=True, null=True)),
                ('genres', models.ManyToManyField(blank=True, to='movies.genre')),
                ('languages', models.ManyToManyField(blank=True, to='management.spokenlanguage')),
            ],
        ),
    ]
