# Generated by Django 4.0.1 on 2022-03-31 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster_path',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='poster_path',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
