# Generated by Django 4.0.1 on 2022-04-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_backdrop_path_alter_show_backdrop_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movie_id',
        ),
        migrations.RemoveField(
            model_name='show',
            name='tv_id',
        ),
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='show',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
