# Generated by Django 4.0.4 on 2022-05-22 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_user_delete_movie_delete_show'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
