# Generated by Django 4.0.4 on 2022-06-01 16:03

import ESGI_Movies.wrappe.tmdb.movies
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0006_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(ESGI_Movies.wrappe.tmdb.movies.tmdb_movie, models.Model),
        ),
    ]
