# Generated by Django 4.0.4 on 2022-06-01 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='adult',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='backdrop_path',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre_ids',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='original_language',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='movie',
            name='original_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='movie',
            name='overview',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='popularity',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_path',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='release_date',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='title',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='vote_average',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='vote_count',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
