# Generated by Django 4.0.4 on 2022-06-08 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_genre_media_type_alter_review_media_type_and_more'),
        ('movies', '0012_remove_movie_genres_alter_movie_genre_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genre_ids',
        ),
        migrations.AddField(
            model_name='movie',
            name='genre_ids',
            field=models.ManyToManyField(blank=True, to='management.genre'),
        ),
    ]
