# Generated by Django 4.0.5 on 2022-06-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_movie_budget_movie_revenue_movie_runtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(blank=True, choices=[('Rumored', 'Rumored'), ('Planned', 'Planned'), ('In Production', 'Inproduction'), ('Post Production', 'Postproduction'), ('Released', 'Released'), ('Canceled', 'Canceled')], max_length=255, null=True),
        ),
    ]
