# Generated by Django 4.0.5 on 2022-06-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0017_alter_movie_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='homepage',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='movie',
            name='tagline',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='movie',
            name='video',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
