# Generated by Django 4.0.5 on 2022-06-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0020_genre_remove_movie_genre_ids_movie_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(blank=True, choices=[('Rumored', 'Rumeur'), ('Planned', 'Planifié'), ('In Production', 'En production'), ('Post Production', 'Post production'), ('Released', 'Sorti'), ('Canceled', 'Annulé')], max_length=255, null=True),
        ),
    ]
