# Generated by Django 4.0.5 on 2022-06-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0021_alter_movie_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='video',
            field=models.BooleanField(null=True),
        ),
    ]
